<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBNgR4G1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBNgR4G1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBNgR4G1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBNgR4G1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBNgR4G1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BNgR4G1',
    'container.build_id' => '3c2f2a34',
    'container.build_time' => 1584701892,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBNgR4G1');
